In [8]:
import numpy as np

v1 = np.array([9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0])
v2 = np.array([9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0])
w1 = np.random.rand(3, len(v1))
w2 = np.random.rand(len(v2), 3)

# dot product of vectors
np.dot(v1, v2)

278

In [6]:
# element-wise product of vectors
v1 * v2

array([81,  4, 10,  0,  0, 63, 10,  0,  0,  0, 81,  4, 25,  0,  0])

In [9]:
# element-wise product of vectors
np.multiply(v1, v2)

array([81,  4, 10,  0,  0, 63, 10,  0,  0,  0, 81,  4, 25,  0,  0])

In [12]:
# outer product of vectors
np.outer(v1, v2)

array([[81, 18, 18, 81,  0, 81, 18, 45,  0,  0, 81, 18, 45,  0,  0],
       [18,  4,  4, 18,  0, 18,  4, 10,  0,  0, 18,  4, 10,  0,  0],
       [45, 10, 10, 45,  0, 45, 10, 25,  0,  0, 45, 10, 25,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [63, 14, 14, 63,  0, 63, 14, 35,  0,  0, 63, 14, 35,  0,  0],
       [45, 10, 10, 45,  0, 45, 10, 25,  0,  0, 45, 10, 25,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [81, 18, 18, 81,  0, 81, 18, 45,  0,  0, 81, 18, 45,  0,  0],
       [18,  4,  4, 18,  0, 18,  4, 10,  0,  0, 18,  4, 10,  0,  0],
       [45, 10, 10, 45,  0, 45, 10, 25,  0,  0, 45, 10, 25,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0

In [23]:
# cross product of vectors, result a vector, which is perpendicular to v1 and v2

np.shape(v1)
v1.reshape((15, 1))
np.shape(v1)

(15,)

In [27]:
np.multiply(w1, v1)

array([[3.5015541 , 1.93306913, 3.6808631 , 0.        , 0.        ,
        6.75807826, 2.29454848, 0.        , 0.        , 0.        ,
        7.68625262, 1.91149312, 2.07047496, 0.        , 0.        ],
       [2.36420494, 1.6840849 , 4.7072198 , 0.        , 0.        ,
        4.4008629 , 1.4529265 , 0.        , 0.        , 0.        ,
        6.34759018, 0.67608288, 1.81407355, 0.        , 0.        ],
       [3.16441354, 1.46860886, 4.86095352, 0.        , 0.        ,
        1.56921882, 4.66673539, 0.        , 0.        , 0.        ,
        8.29936549, 0.35467611, 2.62364131, 0.        , 0.        ]])

In [32]:
np.dot(w1, v1[:,None])

array([[29.83633377],
       [23.44704565],
       [27.00761303]])

In [28]:
np.dot(w1, w2)

array([[2.8157563 , 4.29476544, 3.83455691],
       [2.29481274, 3.44354515, 2.66382001],
       [3.44363454, 4.32893394, 3.24079068]])

In [30]:
np.multiply(w1, w2.T)

array([[0.12183806, 0.13806827, 0.25095597, 0.13786449, 0.23850478,
        0.20431212, 0.18828749, 0.17240312, 0.04270323, 0.12593792,
        0.63010076, 0.02378445, 0.37284743, 0.15094156, 0.01720662],
       [0.11248555, 0.49652473, 0.82692522, 0.13423363, 0.26217997,
        0.52855921, 0.19614677, 0.08713307, 0.13456593, 0.01301103,
        0.22680056, 0.00319429, 0.05016182, 0.07184283, 0.29978054],
       [0.06879529, 0.57096173, 0.08142273, 0.14397046, 0.54692101,
        0.01521715, 0.12656588, 0.32638744, 0.30356555, 0.00938764,
        0.0912353 , 0.17528872, 0.37094587, 0.0629801 , 0.34714582]])

In [34]:
w1 * w2.T

array([[0.12183806, 0.13806827, 0.25095597, 0.13786449, 0.23850478,
        0.20431212, 0.18828749, 0.17240312, 0.04270323, 0.12593792,
        0.63010076, 0.02378445, 0.37284743, 0.15094156, 0.01720662],
       [0.11248555, 0.49652473, 0.82692522, 0.13423363, 0.26217997,
        0.52855921, 0.19614677, 0.08713307, 0.13456593, 0.01301103,
        0.22680056, 0.00319429, 0.05016182, 0.07184283, 0.29978054],
       [0.06879529, 0.57096173, 0.08142273, 0.14397046, 0.54692101,
        0.01521715, 0.12656588, 0.32638744, 0.30356555, 0.00938764,
        0.0912353 , 0.17528872, 0.37094587, 0.0629801 , 0.34714582]])